### ISSUE TITLE
schema.org/mediaType does not exist

### ISSUE THREAD

**Issue by MFSY** [INCF/neuroshapes#110]

**Comment by danbri** [comment]
Hi! We had both fileFormat and mediaFormat in Schema.org, but not mediaType. Our most recent release (3.4, couple weeks ago) merged the two and made "mediaType" the preferred variant. 

http://schema.org/encodingFormat

It is oriented towards MIME media types but also open-ended since there are many formats that haven't been formally registered at IANA (especially scientific formats...).

**Comment by danbri** [comment]
Apologies for the 2nd comment but in case you're reading this in email, where edits don't show up: I just edited my initial comment to fix an unfortunate typo, encodingFormat not mediaType is the preferred term.

Let me add that if you have other suggestions to improve Schema.org based on your work here, we're open to proposals and additions if they're likely to be used in real applications

**Comment by MFSY** [comment]
Hi @danbri ,
Thank you for the heads up about the new schema.org release and the new preferred term http://schema.org/encodingFormat for MIME media types. Very helpful.

We needed a mediaType property in the context of a dataset distribution value, but encodingFormat can definitely be used instead. 
Here is an example of a dataset distribution description we were hoping to build from schema.org: 

```
{
  "@context": "......",
  "@type": "Dataset",
  "name": "My dataset",
  "distribution":{
    "@type":"DataDownload",
    "downloadUrl":"http://url.towards.dataset.binary.io",
    "accessUrl":"http://url.towards.resource.describing.how.to.download.the.dataset.info",
    "mediaType":"application/pdf",
    "contentSize": {
      "@type":"QuantitativeValue",
      "value": 50,
      "unitCode": "mb"
    },
    "digest":{
      "alg":"SHA-256",
      "value":"639e...60cba"
     }
   }
}
```

- I've noticed that [downloadUrl](http://schema.org/downloadUrl) is now introduced in the 3.4 schema.org release, but it is only used in the type [SoftwareApplication](http://schema.org/SoftwareApplication). I'm wondering why such limitation.

- [contentSize](http://schema.org/contentSize) (File size in (mega/kilo) bytes) has Text as expected type.

- digest is not defined in schema.org as far as I know. checksum either is not defined.

Any suggestions or ideas on this is welcomed. 

Also, we noticed that the above json-ld description is for now closer to [DCAT](https://www.w3.org/TR/vocab-dcat/) than to schema.org.

We do have some properties we would love to see added to schema.org or its life science extension. An experimental subject age property is an example. I'll open an issue on schema.org.
