### ISSUE TITLE
type instead of @type in neurosciencegraph/core/data/v0.3.x

### ISSUE THREAD

**Issue by olinux** [INCF/neuroshapes#174]
There is an error in neurosciencegraph/core/data/v0.3.x (compare links below): the property should be named "@type" instead of "type" - this is relevant since this makes everything that imports this context an invalid JSON-LD and prevents us from expanding the context.

https://github.com/INCF/neuroshapes/blob/c616bf796e11ba740ac8e869d98643f72586d0c6/modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.2.json#L11

https://github.com/INCF/neuroshapes/blob/c616bf796e11ba740ac8e869d98643f72586d0c6/modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.1.json#L11

https://github.com/INCF/neuroshapes/blob/c616bf796e11ba740ac8e869d98643f72586d0c6/modules/commons/src/main/resources/contexts/neurosciencegraph/core/data/v0.3.0.json#L11

**Comment by MFSY** [comment]
Hi @olinux,
Thank you reporting this. We usually deprecate older version of a given resource (context, schema) and encourage users to move to latest versions. But I understand the issue here. So I'll fix it.
