### ISSUE TITLE
Docker instance does not return new domains

### ISSUE THREAD

**Issue by ehsanmaag** [INCF/neuroshapes#274]
Hello,
I am using a docker installation of Nexus to create a new domain.
The function Domain.create_new(...) returns the address of the new domain (e.g. <pyxus.resources.entity.Domain at 0x22edb0eb4a8>) however client.domains.read(...) returns None.
Any thoughts on where the issue might be? Any help is greatly appreciated!

**Comment by MFSY** [comment]
Hi,
What are you using to interact with Nexus. I guess it is this tutorial: https://github.com/BlueBrain/nexus/blob/v0/tutorial/basic_operations_nexus_v0.ipynb

If yes, I suggest you open an issue in the corresponding repository: https://github.com/BlueBrain/nexus

And from there, you can get better support.

**Comment by ehsanmaag** [comment]
I am using a notebook to interact with Nexus similar to the tutorial. 
Thank you for your reply, I will open an issue under Nexus repository.

**Comment by MFSY** [comment]
Hi,
I can meanwhile provide some help. 

I expect you use Blue Brain  Nexus v0 (if using Blue Brain Nexus v1 then nothing defined in  [this v0 tutorial ](https://github.com/BlueBrain/nexus/blob/v0/tutorial/basic_operations_nexus_v0.ipynb) will work). The two Blue Brain Nexus versions are not compatible. We are working on a new python notebook for v1 to be released very soon.

Make sure, you run the following instructions when creating a domain in Blue Brain Nexus:


````
organization_name = "myorg"
your_domain = Domain.create_new(organization_name, domain_name, domain_description) 
client.domains.create(your_domain)
````
Note that:

* Domain.create_new(...) will not push any data to Nexus. It will create a python object instead whose data get pushed in Nexus when executing client.domains.create(...).

**Comment by ehsanmaag** [comment]
Thank you, that is correct I am using v0 on docker. Also I am using Domain.create_new(...). 
However the same function call (same params) complete successful on Nexus sandbox at bbp-nexus.epfl.ch/staging and I am able to see the domain created. Do you think there might be a part of service not started/corrupted (so that domain.create_new is successful, but domains.read fails on our docker instance)?

**Comment by MFSY** [comment]
I'm surprised that with just Domain.create_new(organization_name, domain_name, domain_description) you get a domain in the Nexus sandbox. All deployment of our Nexus deployments are working the same way as far as I know. 

Can you check again that you executed client.domains.create(your_domain) after Domain.create_new(...) ?

**Comment by pafonta** [comment]
@ehsanmaag You might find useful what I did there: https://github.com/BlueBrain/nat/blob/master/kg/README.md.

**Comment by ehsanmaag** [comment]
> @ehsanmaag You might find useful what I did there: https://github.com/BlueBrain/nat/blob/master/kg/README.md.

@pafonta Thanks very much for sharing the info on NAT ... that is a very interesting work on use of pipelines for KG data exchange! I will give it a try next.

**Comment by ehsanmaag** [comment]
@MFSY Thank you for helping to resolve the issue. It seems this has been due to an error on my part using non existing Organization name. The issue got resolved after I created the organization.

**Comment by MFSY** [comment]
Excellent.

**Comment by pafonta** [comment]
I was a bit in a hurry yesterday.

> The function Domain.create_new(...) returns the address of the new domain (e.g. <pyxus.resources.entity.Domain at 0x22edb0eb4a8>) however client.domains.read(...) returns None.

It seems, when you said 'address', you were thinking about something related to a distant / network one, but it is a local one and it is not network related. It is just that pyxus does not implement the magic `__repr__` method for the class `Domain` (`Entity`) and what you see is the default Python representation in this case.

> Thanks very much for sharing the info on NAT ... that is a very interesting work on use of pipelines for KG data exchange! I will give it a try next.

I might should have added that with this toolkit I have built to support my work you have '**best ways of doing something**' encapsulated in methods. For example, when you have to create a domain, you can use `create_domain(...)` ([nexus_utils.py#L121)](https://github.com/BlueBrain/nat/blob/f705728f7865c45a1213b0b337f2f29b415c403b/kg/nexus_utils.py#L121) and it will check if the domain already exists, creates the local instance and registers it.

**Comment by ehsanmaag** [comment]
@pafonta That's perfect, thanks!
