### ISSUE TITLE
InvalidSchemaIds for long schema names

### ISSUE THREAD

**Issue by olinux** [INCF/neuroshapes#54]
When trying to upload the schemas to nexus, long schema names cause a 400 error ("invalidSchemaIds") 
Example:  neurosciencegraph/experiment/intracellularsharpelectroderecordedcell/v0.1.0

**Comment by MFSY** [comment]
Okay. This is indeed long. 
@apdavison : Is it possible to shorten this schema name ?

**Comment by apdavison** [comment]
yes, of course, although the name will no longer be as descriptive. How about "intrasharprecordedcell"?

What is the length limit, by the way?

**Comment by olinux** [comment]
intracellularsharpelectroderecordedcellcollection, intracellularsharpelectroderecordedslice and reconstructedcellreleasegeneration are affected as well. I wasn't able to find a limit in the documentation - but reconstructedcellreleaseprocess works, so 31 chars seem to be still fine, 34 not

**Comment by MFSY** [comment]
The limit is 32 actually.

**Comment by apdavison** [comment]
ok, the substitution "intracellularsharpelectrode" --> "intrasharp" brings those to 32 or under - len("intrasharprecordedcellcollection") => 32

@olinux will you like me to make this change, or will you do it?

**Comment by olinux** [comment]
@apdavison I will do it and send it to you for review

**Comment by MFSY** [comment]
Fixed in #59
