### ISSUE TITLE
neurosciencegraph/simulation/emodelgeneration/v0.1.0 references nexus/provsh/generation/v0.1.0 instead of nexus/provsh/generation/v1.0.0

### ISSUE THREAD

**Issue by olinux** [INCF/neuroshapes#57]
The emodelgeneration v0.1.0 schema references the wrong version of generation (v0.1.0 is not part of https://github.com/BlueBrain/nexus-prov ) - it probably should be v1.0.0

**Comment by MFSY** [comment]
Indeed. All prov v0.1.0 schemas were removed from the v1.0.0 release because they cause some validation issues. 

But from the next releases previous schema versions need to be kept (or have the release version consistent with the schemas one).

Will use v1.0.0.

**Comment by MFSY** [comment]
Fixed in #58
